services:
  - type: web
    name: frontend
    runtime: node
    region: frankfurt
    buildCommand: npm install
    startCommand: cd apps/frontend && node server.js
    healthCheckPath: /
    envVars:
      - key: NODE_VERSION
        value: 24
      - key: API_MOBILITY_URL
        fromService:
          type: pserv
          name: api-mobility
          property: hostport
      - key: API_REALESTATE_URL
        fromService:
          type: pserv
          name: api-realestate
          property: hostport

  - type: pserv
    name: api-mobility
    runtime: node
    region: frankfurt
    buildCommand: npm install
    startCommand: cd apps/api-mobility && node src/server.js
    envVars:
      - key: NODE_VERSION
        value: 24

  - type: pserv
    name: api-realestate
    runtime: node
    region: frankfurt
    buildCommand: npm install
    startCommand: cd apps/api-realestate && node server.js
    envVars:
      - key: NODE_VERSION
        value: 24
